version: '3.8'

services:
  xfcevdi:
    image: le91/xfcevdi_x2go:latest
    tty: true
    container_name: le91_vdi
    restart: unless-stopped
#    networks:
#      - xfce_vdi_network
    environment:
      USERNAME: le91
      PASS: abc
      # ENTER_PASS: 'yes'
      # ALLOW_APT: 'no'
    volumes:
      # Make home mount persistent across restarts
      - ./home_storage:/home
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 2048000000 # 2GB
    ports:
      - '2244:22'

#networks:
#  xfce_vdi_network:
